name: Test
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        run: |
          # Fail on any lint errors
          uv run ruff check .
  test:
    name: python
    needs: lint
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            python-version:
                - '3.9'
                - '3.11'
                - '3.13'

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest tests -vv -s